### ISSUE TITLE
請問此輸入法可以繁體簡體切換輸入嗎?

### ISSUE THREAD

**Issue by dasu88** [yurenli0217/Boshiahk2#1]
如題，請問此輸入法可以繁體簡體切換輸入嗎?

**Comment by yurenli0217** [comment]
我有提供一個打繁出簡的表格，預設是用 ,,c 切換，您可以試試看喔。
之後再用 ,,t 切換回來繁體中文的表格即可。

**Comment by dasu88** [comment]
> 我有提供一個打繁出簡的表格，預設是用 ,,c 切換，您可以試試看喔。
> 之後再用 ,,t 切換回來繁體中文的表格即可。

試出來了，謝謝你，另提供一個小建議不知能否達成，敬請參考：
希望在輸入法icon上按右鍵對應的不是程式的關閉，而是可以有其他功能性的切換表單。
比較符合一般輸入法的操作模式，不然我常常無意識的把它關閉了。

此程式很棒，謝謝你

**Comment by dasu88** [comment]
另外、突然想到，上述的切換繁簡的快捷鍵，可否調整為：
,,ct 為切換繁轉簡?? 
雖然官版也有,,c切換為簡體，但實際上,,ct才是打繁轉簡…
我不知道實際使用上是否有差異，但操作習慣了，就一直是用
,,ct切換。

**Comment by yurenli0217** [comment]
可以的，您在 INI 檔內調整切換表格的功能碼即可，把 ,,c 改成 ,,ct。

**Comment by yurenli0217** [comment]
> 試出來了，謝謝你，另提供一個小建議不知能否達成，敬請參考：
> 希望在輸入法icon上按右鍵對應的不是程式的關閉，而是可以有其他功能性的切換表單。
> 比較符合一般輸入法的操作模式，不然我常常無意識的把它關閉了。
> 此程式很棒，謝謝你

這個操作方式我要再想想看有什麼東西可以放在表單。
