### ISSUE TITLE
2022-09-04 二次更新版本問題報告

### ISSUE THREAD

**Issue by mackuo** [yurenli0217/Boshiahk2#12]
感謝作者提供這麼好用的程式，造福蝦米族。
2022-09-04 二次更新後，在Line的文字回覆及Microsoft Word中，只要打「，」這些程式自己預判可能會修正的字元時，
就要先按「Enter」鍵，將「，」送出，不然「，」就會出現在打完所有的中文字的最後面。
不曉得是我個人的問題，還是程式更新的問題。

我另外一台電腦用舊版是不會有上述問題的。

**Comment by yurenli0217** [comment]
您好，我在Line和Word中測試輸入的情況是正常的，系統在倉頡輸入法的英數模下，以及在ENG的模式下都測試過，可以正常輸入逗號。

**Comment by mackuo** [comment]
感謝快速回覆，我後來查到原因了。我是用新注音在「英文」模式下來操作蝦米殼。因為新注音裝好後，會自動開啟一些「自動化學習」、「個人化學習」還有「使用者造詞」等功能，我把這些功能全關了之後，操作就正常了!!
再次感謝!!

**Comment by mackuo** [comment]
已解決!!
