### ISSUE TITLE
2022-09-11 版本，執行遇到的問題

### ISSUE THREAD

**Issue by lalarun** [yurenli0217/Boshiahk2#13]
2022-09-11 版本，使用過程中，遇到好幾次如下圖的程式出錯，請作者看一下
![Error](https://user-images.githubusercontent.com/25225032/192737077-91707e51-34e4-456a-8429-13c339b785a9.png)

**Comment by yurenli0217** [comment]
您好，我有先釋出新版，請您協助測試看看。
若有出現無法抓取視窗的訊息，請協助將當時的操作狀況回報給我，謝謝您。
