### ISSUE TITLE
標點符號無法按空白鍵後上字

### ISSUE THREAD

**Issue by charce1103** [yurenli0217/Boshiahk2#15]
標點符號 例如打 ,+空白鍵，無法自動上字，而需要按 「 , + space + enter 」才會上字
其他標點符號也有類似的問題，不知大家是否有同樣的問題

**Comment by yurenli0217** [comment]
您好，我目前使用都很正常，您看看系統的輸入法狀況是否在英文(美國)鍵盤或是微軟倉頡?

**Comment by charce1103** [comment]
感謝，原先預設輸入法安裝的是微軟注音，新增並切換到微軟倉頡後，就解決問題了，感謝。

**Comment by ffspan** [comment]
![image](https://user-images.githubusercontent.com/123629520/214801114-5e6f0f24-7f00-4314-94ef-7743f7099201.png)

測試的結果。在win10 環境。

**Comment by yurenli0217** [comment]
你好，這是在系統為倉頡輸入法時才會遇到的問題，目前無解，我的做法是在line中輸入文字時，系統輸入法狀態改成英文鍵盤。

**Comment by ffspan** [comment]
還是先謝謝，作者的開發讓我們免費使用。
回報問題能解決是最好，不然也就是這樣用，只是習慣性的問題。
我個人是會在 line ,word ,notepad，三個環境輸入，才發現不同的狀況產生。

**Comment by yurenli0217** [comment]
您好，您可以試試將倉頡改成速成，試試看是否可以解決重複送符號的問題，我這裡試過可以解決，目前我也是將系統輸入法改成速成，後續我在更新時會一併更新說明網頁，這裡先跟您回覆。
