### ISSUE TITLE
無法在  oblivionburn realai 中使用

### ISSUE THREAD

**Issue by tino926** [yurenli0217/Boshiahk2#16]
在 oblivionburn realai (https://oblivionburn.itch.io/realai) 中會完全無法使用。
當 realai 視窗為焦點時，無法切換到嘸蝦米，
若先切換到嘸蝦米再切到realai視窗，打出來的是英文。

**Comment by yurenli0217** [comment]
有些程式好像支援 TSF 輸入，不過我對於 TSF 是不懂的，所以可能無法在一些程式上輸入中文，不好意思。
