### ISSUE TITLE
初次使用時，若Windows工具列在左或右，輸入法狀態提示列無法正確顯示

### ISSUE THREAD

**Issue by atheoshgv** [yurenli0217/Boshiahk2#18]
首次使用時，若Windows工具列在左或右，輸入法的狀態提示列無法顯示(但輸入功能正常)，需把工具列拉到上或下，重開輸入法
調整好工具列及狀態提示列位置後，再重開輸入法記錄位置才會正常，雖只有第一次需調整但當初使用也是摸索很久才找到狀態提示列消失的原因，希望能改進這個問題。

另外建議切換表格(簡體、日文、韓文)是預設開啓，畢竟會鍵入,,C、,,T、,,J、,,K的使用者大部份都不是誤按而是有該功能的需求。

最後感謝作者開發了這麼好用的輸入法，加油！！

**Comment by yurenli0217** [comment]
您好，這個原因是程式在一開始會判斷工具列高度，但當時我的程式判斷只有針對工具列在下的情況，在上、左、右沒有加入判斷，所以會導致顯示的位置會看不到，後續有機會的話，我再修改看看，謝謝回報。

**Comment by yurenli0217** [comment]
此問題已在新版中嘗試修正。
