### ISSUE TITLE
冒號無法呈現

### ISSUE THREAD

**Issue by MrLuke1110** [yurenli0217/Boshiahk2#19]
英數或蝦米模式底下，按「shift+;」，無法顯示「:冒號」，出現都是「;分號」，再麻煩確認
已更新 2023-03-04的版本

**Comment by yurenli0217** [comment]
您好，我剛有測試，Shift + 分號可以正常送出冒號。
系統輸入法在 ENG 即英文鍵盤的模式下測試正常。

**Comment by MrLuke1110** [comment]
謝謝~ 我重開機之後好像也正常…
