### ISSUE TITLE
嘸蝦殼2問題與建議回報

### ISSUE THREAD

**Issue by mega5241p** [yurenli0217/Boshiahk2#2]
作者您好
1003版目前發現無法打出全形驚嘆號（！）及全形問號（？）
可能是新的表格檔未收錄的關係吧…

字體設定方面，發現小瀨字體（小賴字體 SC倒是正常）、Source Han Sans不能正常套用，需找到字檔型查詢視窗內字型名或是視窗標題欄的名稱才可能正常套用，其他字型也可能有這樣的問題，沒有一一檢查（字型太多了，只試了自己常用的XD）

另，希望能再做出同音字查詢功能，且可自訂其熱鍵
還有能像前一代將字根區的「嘸」字隱藏及游標跟隨模式，設定可開關（讓只有一個螢幕且能正常使用跟隨的人多個選擇，預設關閉即可，需要的人自訂），以滿足個人喜好，感恩！

**Comment by yurenli0217** [comment]
您好，先謝謝您的回報。

表格檔這兩個符號確實沒有收錄到，我後續會補上，整理表格檔不是很好做的事，難免會有缺，還請您見諒。

Autohotkey GDI+ 相關的調用全部都是使用 Windows 10 系統的 API，我自己的測試過程中，有的字體必須要開啟字型檢視的程式，看其字型的全部名稱，才能正確調用字型。

同音的字功能還在構思，因為上一版做的不好，想要試著改善，而不是匆忙地趕一個不好用的功能出來，還請您等待。

這一版的跟隨游標我應該是不會弄了，跟您說聲抱歉喔，原因是支援度太差，但是我可以做到隱藏「嘸」，這會加入未來開發的規劃。

**Comment by mega5241p** [comment]
了解！感謝作者回覆！
剛要打日文假名發現無法打出來
判斷可能還是未收錄在中打的表格檔或是符號表格裡吧…
基本上在官蝦的中打模式中預設是可以打出日文假名，而不需要特地切換到日文模式
希望下個版本在中打模式也能打出假名，謝謝

**Comment by yurenli0217** [comment]
您好，新的表格檔內因為在預設的表格內已經將日文假名拿掉了，只保留在日文模式內，如果您需要在預設表格內也能夠打出假名，就需要換回先前版本的表格檔。
目前表格檔是蝦友 Fairry 花時間無私整理的，這裡我會先尊重他整理表格的想法，因此我將他整理的舊版和新版表格都提供在網站上，給不同需求的使用者下載。

**Comment by manao29** [comment]
和作者大大反饋下，浮動窗格「嘸」可否跟隨打字時的文字做動態下移調整呢，因為有時會擋住當前欄位。謝謝啦^^

**Comment by manao29** [comment]
和作者大大反饋下，浮動窗格「嘸」可否跟隨打字時的文字做動態下移調整呢，因為有時會擋住當前欄位。謝謝啦^^

**Comment by yurenli0217** [comment]
manao29您好，在AHK2下我目前只能做到跟隨螢幕的功能，跟隨游標在 AHK2 下還沒有比較完善的解決方式，建議可以將ShowStates設定成0，只在有輸入字根時顯示介面，這樣子就不會在沒有輸入的情況下擋住畫面了。

**Comment by manao29** [comment]
> manao29您好，在AHK2下我目前只能做到跟隨螢幕的功能，跟隨游標在 AHK2 下還沒有比較完善的解決方式，建議可以將ShowStates設定成0，只在有輸入字根時顯示介面，這樣子就不會在沒有輸入的情況下擋住畫面了。

我照您説的試了下，效果還蠻不錯的！十分感謝！^^

**Comment by manao29** [comment]
作者您好，在我原來解析度比較低(1366*768)的電腦上，這個小工具使用起來很不錯，但在我的另一台更高解析度(好像是2736*1824)的螢幕上，浮窗「嘸」顯示為一個小圓點，調整FontSize之后依然如此，想問一下這是怎麼回事呢，還需要調整哪些設定嘛？

**Comment by manao29** [comment]
作者您好，在我原來解析度比較低(1366x768)的電腦上，這個小工具使用起來很不錯，但在我的另一台更高解析度(好像是2736x1824)的螢幕上，浮窗「嘸」顯示為一個小圓點，調整FontSize之后依然如此，想問一下這是怎麼回事呢，還需要調整哪些設定嘛？

**Comment by yurenli0217** [comment]
你試著把字型名稱改成標楷體看看，我之前遇到小圓點的情況是系統沒有我在 INI 檔內設定的字型名稱。

**Comment by manao29** [comment]
好的，我安裝了兩個全字庫正楷體之后OK了，這個小工具真的太好用，萬分感謝!

**Comment by yurenli0217** [comment]
使用程式下去做這個功能，是能夠做得出來，但是前期的表格檔處理會花很多時間載入，因為要一字一字判斷，程式效能會低下，使用起來就不順手了。
我可以提供另一種方式，就是直接過濾掉Ext-A和Ext-B的字集，我在網路上放的 Table2 的資料夾就是舊的，字集有參考自以前官方的嘸蝦米表格內容，您可以將預設的表格替換成 LiuCJK.txt，這樣子就只會有常用字的選項了。

設定值可以這樣子用:

`default = ..\Table2\LiuCJK,嘸`

**Comment by manao29** [comment]
剛試過可以啦！沒想到這麼輕鬆就解決了，非常感謝您！哈哈^^

**Comment by mega5241p** [comment]
作者您好
目前發現20230102版本有若干問題及建議

1.發現在切換為繁中輸出以外的表格後，無法調用自訂字詞（但V1舊版可以）。

2.是否能增設提示拆碼的Style字型等樣式設定，或是直接跟字根或選字區相同也OK。

3.當設定組字區「嘸」這個狀態為隱藏時，若切換表格或是全型半型後，沒辦法第一時間看出目前狀態，希望能恢復右下系統列各表格的系統圖示（目前只有ON與OFF兩種，無法辨示其他表格或全/半型狀態。

4.一個老遊戲的FEZ中國版本無法在創角時輸入名字、創部隊時也不行，但聊天等沒問題，不過也不是一天到晚都在創角創部隊，影響不大，奇摩輸入法倒是可以在該狀態下輸入，不處理也沒關係吧！只是提出有這問題而已XD（已有用ClipAuto，也才能聊天輸出）

**Comment by yurenli0217** [comment]
您好，目前系統圖示的部分尚在研究中，AHK 2.0 呼叫 API 方式不太一樣我還不是很熟悉，如果有機會我也會想試著做出來也比較方便。
拆碼提示的部分我會考慮看看，因為主要是查詢用的，所以我目前只有提供字型大小的設定。
