### ISSUE TITLE
中英切換觸發設定為LSHIFT常常沒反應

### ISSUE THREAD

**Issue by MrLuke1110** [yurenli0217/Boshiahk2#20]
中英切換觸發設定為LSHIFT時，常常按了沒有反應，要按好幾下才可以切換
但是設定成別的按鍵可以正常運作，系統是WIN10

**Comment by yurenli0217** [comment]
您好，您可以把不觸發的時間設定長一點，這樣子的話應該可以解決這個問題。
預設100ms對於一些使用者來說時間太短了，您可以改成200ms試試看。

**Comment by MrLuke1110** [comment]
> 您好，您可以把不觸發的時間設定長一點，這樣子的話應該可以解決這個問題。 預設100ms對於一些使用者來說時間太短了，您可以改成200ms試試看。

感謝回覆，設定成200ms就正常了，原來是這個原因，難怪按了沒反應又一直連點沒反應…
