### ISSUE TITLE
 嘸蝦殼的加字加詞檔能不能調高上限

### ISSUE THREAD

**Issue by addy1975** [yurenli0217/Boshiahk2#24]
嘸蝦殼很好用，先謝謝作者。
最因為 chatgpt 大量使用，
突然有一個想法，把專用的 Prompt  直接用在加字加詞上，會是無敵的功能。
現在遇到的狀況是 ，當 prompt 太長的時候，嘸蝦殼的自定加詞就無法產生作用，
能不能請作者開放加字加詞的上限呢 ?

比方講，我這樣子的自訂詞太長，就無法作用。<BR>
,ttt
請直接翻譯下面文章，直接翻譯完之後，再給我重新意譯之後的成果，每輪翻譯後，都要重新比對原文，找到扭曲原意或者遺漏的內容，然後再補充到下一輪的翻譯當中（也就是 Chain of Density 概念）。​遵守原意的前提下讓內容更通俗易懂。

**Comment by yurenli0217** [comment]
這段文字可以正常輸出，您只要把空白符號改成「\s」即可。

**Comment by addy1975** [comment]
大成功， 加 \S 就不會被中斷輸出了，無蝦殼真的超強，最好用的第三方蝦米

**Comment by trevim99** [comment]
嘸蝦殼超強的!!
