### ISSUE TITLE
偶爾無法使用SHIFT+；輸入：(半形)符號

### ISSUE THREAD

**Issue by Neo66623** [yurenli0217/Boshiahk2#26]
您好，謝謝您開發的嘸蝦殼，真的非常好用

最近使用時，發現一個小問題，詳述如下
使用嘸蝦殼V2時，會發生無法用SHIFT+；輸入：(半形)符號
不論在英文或中文的模式下，按SHIFT+；，都只會出現；(半形)

但測試了一下，一直找不到會觸發這個狀況的機制

**Comment by yurenli0217** [comment]
目前我也還沒有遇到這樣的情況，如果有遇到我會再試試看，謝謝。

**Comment by ZhenYou-Chen** [comment]
> 目前我也還沒有遇到這樣的情況，如果有遇到我會再試試看，謝謝。

借版留言 
請問大佬 在加字加詞中 是否無法使用+號呢
單打+出不來 打+接數字會變成數字鍵上的符號
例如+4會變$
加字加詞越用越著迷 一堆常用字串 網址都塞了進去
這幾天懶到連帳號密碼都想加進來用了

**Comment by yurenli0217** [comment]
要輸入+號，在AHK中是用可以用+=組合鍵，+在AHK中是代表Shift
