### ISSUE TITLE
Error on line 567; (1461) 不正確的監視器控制代碼

### ISSUE THREAD

**Issue by Neo66623** [yurenli0217/Boshiahk2#28]
今天去開會，回到座位上，插上透過HDMI連接的外接營幕時，跳出以下錯誤(如圖片)
提供給您參考，謝謝

(按下確定後，嘸蝦殼仍可正常使用)

![嘸蝦殼_ERROR_2023-12-19_143812](https://github.com/yurenli0217/Boshiahk2/assets/150758305/7061102b-d1f4-4729-b50c-1be1a1ae6e20)

**Comment by yurenli0217** [comment]
這是因為外接螢幕在做切換時，會有一小段時間，無法取得螢幕資料，我之後會再做修改。
下次的改版會變成這樣: 外接螢幕或是變更螢幕數量，先把嘸蝦殼啟用狀態關閉再外接或變更，應該就不會有問題了。

**Comment by Neo66623** [comment]
好的，再麻煩您了，謝謝
