### ISSUE TITLE
關於注音模式

### ISSUE THREAD

**Issue by mega5241p** [yurenli0217/Boshiahk2#30]
作者您好：
不知是否能做個設定，讓在切換注音模式後，固定此輸入模式，而不是只能輸入一個字就自動恢復成嘸蝦米模式。
這樣除了可以方便查詢多個字詞，不需再多次切換輸入法，也可以讓此輸入法變成雙刀流使用。謝謝！

**Comment by yurenli0217** [comment]
這個功能我會考慮之後試試可否實作，並且當做一個設定選項做切換。

**Comment by mega5241p** [comment]
作者您好：

想說若目前無法實作固定注音模式的話，以自訂加入表格功能來使用注音輸入，但這樣的話，似乎鍵盤的第一排（有數字/ㄅㄉ…的那排）無法拼音使用，而且在字根/拼字區無法顯示注音符號（只有英數），不知是否能解決以上問題而當做備用方案。

另外發現在20240901版本若啟動後，第一次切換注音模式輸入時，「有機會」無法以空白鍵輸出中文，或是無法正常拼音（第二個拼音會重覆成第一個，如要拼「生」字會變成ㄕㄕ），重新啟動後可能又會正常。

**Comment by yurenli0217** [comment]
您好，您的問題我已經得知了，進期會抽空尋找並修正這個問題，謝謝您。

**Comment by GhostShadow0316** [comment]
請問這個功能完成了嗎？
我用最新的 v2024/10/07 似乎還是沒有解決耶
