### ISSUE TITLE
關於選字框自動跟隨 游標 位置 

### ISSUE THREAD

**Issue by amosfan** [yurenli0217/Boshiahk2#32]
請問選字框的位置有辦法自動跟隨 游標 位置 附近嗎？

因為在youtube 找不到示範影片， 
不知道 選字框 是否是永遠 固定在某位置？(即使能拖動 還是不方便)

如果能夠跟隨遊標 位置 附近 (如自然輸入法) 那就太好了!

**Comment by yurenli0217** [comment]
您好，跟隨游標在 AHK v2 中，功能還沒辦法很完善，所以我暫時還是會將輸入介面跟隨在焦點視窗所在的螢幕上。
