### ISSUE TITLE
建議 可以加上 形碼置換的功能

### ISSUE THREAD

**Issue by amosfan** [yurenli0217/Boshiahk2#33]
如果可以客制拆碼時，
輸入的  英文字 自動換成 指定的 拆碼符號的話，
對其它形碼使用者來說，
會更直觀。

例如 
輸入 h 顯示的是 "竹"
輸入 j 顯示的是 "十"

這樣其它非嘸蝦米的使用者 (例如倉頡類的使用者)
就能用此輸入法當作載體，
將之客制成任何形碼輸入法。

**Comment by yurenli0217** [comment]
您好，這一個方案我有想過，但是主要還是以嘸蝦米使用者為主，因為數字鍵的功能在嘸蝦米是做為選字，非字根。
