### ISSUE TITLE
若以shift為開啟/隱藏嘸蝦殼的切換鍵，影響shift其他一般功能的使用

### ISSUE THREAD

**Issue by nomoonwater** [yurenli0217/Boshiahk2#35]
嘸蝦殼預設Ctrl_Space為開啟/隱藏輸入法視窗的切換鍵，
選項可以改成單以LShift為切換鍵（另將中英切換改為其他按鍵），
單按LShift即可隱藏嘸蝦殼，
然後在windows的英文語系狀態下，做英數的輸入，
但此時涉及LShift的任何組合鍵，或是要LShift+上排數字鍵輸出半形符號，
都無法使用了，
因為只要一按LShift就是一直在重覆嘸蝦殼視窗的開啟/隱藏，
（以Ctrl為切換鍵也是一樣情形）

因為相較於偽蝦米，不會有這種情形，
剛好個人是習慣以隱藏中文輸入法視窗來做英數輸入，
又希望單按Shift或Ctrl就可以隱藏嘸蝦殼視窗，
所以請教是否能讓shift或ctrl按下並釋放後，才觸發嘸蝦殼視窗的開啟/隱藏的行為？
（※我試過功能設定勾選「等待Ctrl/Alt/Shift釋放再執行熱鍵功能」並無效果）

以上小小願望。
另外非常感謝大大開發的嘸蝦殼讓大家能繼續爽爽用無蝦米。

**Comment by yurenli0217** [comment]
您好，您的建議我會試試看能否做出來。
