### ISSUE TITLE
2024/09/01 版本無法使用，開啟錯誤

### ISSUE THREAD

**Issue by FZ500** [yurenli0217/Boshiahk2#36]
![image](https://github.com/user-attachments/assets/f11d440d-e452-4c23-8e32-5f11922fe789)
試過二台電腦開啟都這樣

**Comment by yurenli0217** [comment]
您好，我在我的電腦上面測試沒有問題，詳細原因我暫時找不出來，有沒有可能是 UPX 壓縮執行檔造成的，您可以試著用 UPX 解壓縮執行檔看看能不能執行。

**Comment by FZ500** [comment]
有試過UPX解壓後的去運行，結果一樣，但同樣的二台電腦跑2024.05.16都正常，運行2024.09.01的就出錯，好像在特定環境下就會出錯，試了一個全新的系統就正常，不知和下面文章最後的說明有沒有關係。
https://www.autohotkey.com/board/topic/60237-could-not-extract-script-from-exe/

**Comment by FZ500** [comment]
10/07 版本測試正常，無上述產生的錯誤訊息
