### ISSUE TITLE
注音查碼跳出視窗

### ISSUE THREAD

**Issue by shinnlu** [yurenli0217/Boshiahk2#6]
我原本使用 2021-10-21，在注音模式下的畫面如下
![image](https://user-images.githubusercontent.com/570246/163353948-49a80823-a615-41f8-b9bc-cc4717fc4e62.png)
剛剛下載了 2022-04-03，卻跳出一個 Dialog，會影響後續的輸入
![image](https://user-images.githubusercontent.com/570246/163354120-39009046-91fb-4adc-9c44-52d66afd2917.png)
請問要如何改回原本的顯示方式?

**Comment by yurenli0217** [comment]
您好，原本的注音模式是用來查碼的，因為舊的方式顯示拆碼，在拆碼太長的的情況下介面會出錯，所以我後來改成查碼後，會跳出視窗顯示該字所有的拆碼。
