### ISSUE TITLE
程式啟動後，輸入法可以預設是「關閉」嗎？

### ISSUE THREAD

**Issue by lalarun** [yurenli0217/Boshiahk2#7]
很感謝 yurenli0217  開發這麼棒的輸入法，實在太好用

目前電腦每次開機時，設定好捷徑，自動執行這個程式
不過，剛開機時，通常還不需要輸入中文，所以，開機後，要再按一次 Ctrl + Space 來關閉輸入法

是否可以，增加一個設定，來控制，程式第一次啟動時，是否直接「開啟」輸入法

目前的狀況，是直接開啟
如果有設定，可以控制成「關閉」，這樣開機時，啟動程式後，只會讓程式出現在右下角的 tray area

**Comment by yurenli0217** [comment]
INI檔內有一個設定值 StartHidden，設定成1就可以預設隱藏啟動哦。

**Comment by lalarun** [comment]
才剛要上來回報，已經有找到

沒想到，作者馬上親自回答

真心感謝
