### ISSUE TITLE
是否可以設立，捐款贊助開發的機制

### ISSUE THREAD

**Issue by lalarun** [yurenli0217/Boshiahk2#8]
昨天提問，作者馬上回答，可以看到，作者真的用心開發維護，願意傾聽，使用者的聲音

千言萬語，不如用實際捐款，贊助作者持續開發，小弟過去實際捐款的免費軟體有好幾個，例如：
Notepad++, FastStone Image Viewer, 等等  (有捐助過的，都存活至今)

觀察現在網路上的軟體，持續開發精進的，真的不多
常常最初一頭熱，然後，開發者被後續的維護、更新，壓得喘不過氣
就更別提，偶爾會有少數無理取鬧的使用者，隨意謾罵

此時，來自使用者的實際捐款，就是開發者最有力的支持

**是否請作者，設立接受捐款贊助的機制**
小弟願意做第一個捐款的人，金額雖然不高，可是，心意無價

希望作者，能持續維護下去，不要最後又放生

**Comment by yurenli0217** [comment]
您好，我自己在用嘸蝦米，程式我自己也在用，基本上不會放生，沒有更新就是沒有遇到大問題，或者是我沒遇到問題。
把程式寫好是我的目標，並且對我也是有好處的，我現在已經沒有在使用偽蝦米了。

輸入法的功能我都會抽空去慢慢累加，大部分是利用我的空檔時間去做。

我不會需要任何的捐款，我只是單純想為著嘸蝦米輸入法的使用者在使用任一台電腦的情況下，還能有一個選擇。

若是您真的願意表達感謝，我還蠻喜歡食物類的，若是可以寄一個好吃的當地名產給我，我就很開心了，我從事物流業者，您若是願意寄來，我可以請託同事幫忙，不用讓您花費任何運費。
