### ISSUE TITLE
「孟」的拆字，無法打「ZFEV」

### ISSUE THREAD

**Issue by lalarun** [yurenli0217/Boshiahk2#9]
「孟」的拆字，無法打「ZFEV」，只能用「ZFE」再加上號碼「1」來選字
單純打「ZFE」的時候，「孟」會出現在第 1 個候選字，一般而言，加「V」就可以選

是否有設定要改，才能直接用「ZFEV」來打出「孟」呢？

**Comment by yurenli0217** [comment]
您好，zfev 無法出「孟」字的原因是表格檔的問題，如果使用新式的表格檔，因包含了很多Unicode的文字，而zfev剛好又有對應的字，所以變成無法像舊式的表格檔對應到zfe的第二選字。
您可以將表格檔設定改成舊的，即Table2目錄裡面的檔案，用舊式的表格檔就可以用zfev打出「孟」。

**Comment by lalarun** [comment]
真心感謝作者，快速的回答

請問在  Boshiahk2.ini 檔案中，如何將表格檔，設定成 Table2 下面的檔案呢？

有試過  在 [Table]的下方改成
default = LiuCJK,嘸

程式會說，表格檔 table\LiuCJK.txt 不存在

**Comment by yurenli0217** [comment]
您直接將 Table2 資料夾改為 Table，再指定就可以了。

**Comment by yurenli0217** [comment]
您好，我今日有將程式更新，將表格檔對應預設改為舊式的字碼表，您使用起來應該會比較順手一點。

**Comment by a9202507** [comment]
感謝，我也有用v選第一個字的需求，下載0627版本後，已經可以了。

謝謝大神。
